[tool.poetry]
name = "gigacommit"
version = "0.1.0"
description = ""
authors = ["Roman Sotnikov <axeman.ofic@gmail.com>"]
readme = "README.md"
packages = [{include = "src", from = ""}]

[tool.poetry.dependencies]
python = "^3.12"
gigachat = "^0.1.16"
typer = {extras = ["all"], version = "^0.9.0"}
platformdirs = "^4.2.0"
rtoml = "^0.10.0"

[tool.poetry.scripts]
gc = "src.__main__:app"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
